# Default Scene Configuration for Himalayan Landscapes Visualization

Run:
  SceneName: "Himalayan Valley"
  SceneDescription: "Default visualization of a Himalayan mountain landscape"
  GlobalScale: 1.0
  RandomSeed: 12345
  TimeOfDay: 10.0
  EnableSimulation: true
  SimulationSpeed: 1.0

Window:
  Width: 1280
  Height: 720
  Fullscreen: false
  Title: "Himalayan Landscapes"
  VSync: true
  MsaaSamples: 4
  BackgroundClearColor: [0.5, 0.6, 0.7, 1.0]
